name: LevelUPSystem
main: LevelUPSystem\Main
api: [3.0.0, 4.0.0]
version: 1.0.0
author: ZayDepths Development

depend: [FormAPI]
commands:
 profile:
  description: Shows your current level and statistics
  default: true
 levelup:
  description: Levelup with your current available xps
  default: true
  aliases: [lvlupgrade, upgradelvl, upgrade, lvlup]
